### ISSUE TITLE
Shariff without jQuery, just vanilla JavaScript

### ISSUE THREAD

**Issue by markseu** [schulle4u/yellow-plugin-shariff#3]
Hi Steffen, 

how about Shariff without jQuery, see [jQuery dependency #251](https://github.com/heiseonline/shariff/issues/251). 

If I understand this correctly, we could simply replace `shariff.min.js` with `shariff.complete.js`. It's 4KB bigger but saves an external HTTP request. Probably should name it `shariff-complete.min.js`, as far as I can see the file is already minified, then the [file bundler](https://github.com/datenstrom/yellow-plugins/tree/master/bundle) knows to not minify it again.  

What do you think?

**Comment by schulle4u** [comment]
Hi Mark, 

yes, it is a good idea to remove external ressources when there are better alternatives available. An extra 4 KB really won't hurt that much. I'll give it a try later this day. 

Steffen

**Comment by markseu** [comment]
Yes it works and page loads fast.
